import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "MyIkame",
  // description: "Generated by create next app",
  icons: {
    icon: "./icons/logo.svg",
    shortcut: "./icons/logo.svg",
    apple: "./icons/logo.svg",
  },
};

const inter = Inter({
  subsets: ["latin"], // Specify subsets if needed (e.g., latin, latin-ext)
  weight: ["400", "500", "600", "700"], // Define the weights you want to use
  variable: "--font-inter", // Optional: to create a CSS variable
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F4F5F5]">
        <main className={inter.className}>{children}</main>
      </body>
    </html>
  );
}
